Header header

int16       UAV_status
string      flight_mode
float32     flight_time
float32     battery_voltage
float32     cpu_load
float32     up_time

bool        serial_interface_enabled
bool        serial_interface_active

string      motor_status

uint8       ctrl_mode
uint8       ctrl_enabled
uint8       disable_motor_onoff_by_stick
uint16      waypt_status

uint16      debug1
uint16      debug2
uint16      debug3

string      gps_status
int32       gps_num_satellites

